### ISSUE TITLE
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by sujithgunturu** [openalea-incubator/adel#20]
from alinea.adel.astk_interface import AdelWheat
from alinea.astk.Weather import sample_weather
seq, weather = sample_weather()
wdata = weather.get_weather(seq)
adel = AdelWheat(nsect=2)
g = adel.setup_canopy(100)
adel.grow(g, wdata)

Getting the error:

(adel) C:\Users\Personal\Desktop\OpenAlea research\adel\example>python test_AdelWheat.py
Traceback (most recent call last):
File "test_AdelWheat.py", line 1, in
from alinea.adel.astk_interface import AdelWheat
File "C:\Users\Personal\Desktop\OpenAlea research\adel\src\alinea\adel\astk_interface.py", line 6, in
from alinea.adel.AdelR import setAdel, RunAdel, genGeoAxe, checkAxeDyn, getAxeT,
File "C:\Users\Personal\Desktop\OpenAlea research\adel\src\alinea\adel\AdelR.py", line 23, in
import rpy2.robjects as robj
File "C:\Users\Personal.conda\envs\adel\lib\site-packages\rpy2\robjects_init_.py", line 16, in
import rpy2.rinterface as rinterface
File "C:\Users\Personal.conda\envs\adel\lib\site-packages\rpy2\rinterface_init_.py", line 92, in
from rpy2.rinterface._rinterface import (baseenv,
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

**Comment by pradal** [comment]
This is due to a problem with RPy2 package.

Can you test:

import rpy2.robjects as robj

To see if this line fail?
Thanks

Le 05/03/2020 à 07:18, sujithgunturu a écrit :

**Comment by sujithgunturu** [comment]
I am getting DLL for **import rpy2.robjects as robj** and also **import alinea.adel.AdelR**

**Comment by ShichaoJin** [comment]
> I am getting DLL error for **import rpy2.robjects as robj** and also **import alinea.adel.AdelR**

you can install rpy2 from here, https://www.lfd.uci.edu/~gohlke/pythonlibs/#rpy2

**Comment by sujithgunturu** [comment]
First import statement fails 9 out of every 10 times. And sometimes scene is not generated.

**Comment by sujithgunturu** [comment]
> First import statement fails 9 out of every 10 times. And sometimes scene is not generated.

Import alinea.septo3d is failing (import error for septo3d) any command to install septo3d?

**Comment by sujithgunturu** [comment]
Issue solved
